/**
 * A typed reader for the `*_atlas.json` files in `Art/`.
 *
 * Every sheet there is already packed — a grid of `cell_width` by
 * `cell_height` cells, one sprite per cell — so this reads, it never cuts or
 * packs. It keeps the optional fields some sheets carry rather than dropping
 * them, since they are what tells the renderer a sprite is a repeatable stroke
 * (`tiles`, `centerline_y`) or a die face (`role`, `value`) instead of a
 * one-shot image.
 *
 * A sheet is found by its **file name**, `<Name>_sheet.png` beside
 * `<Name>_atlas.json`, not by the atlas's own `sheet` field: five of the
 * supplied atlases name a file that was renamed on the way into `Art/`
 * (`Forest_Trees_atlas.json` says `trees_sheet.png`, for one), so the field is
 * kept as `sheetField` for reference and read for nothing.
 */
export interface AtlasSprite {
  readonly id: string;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
  /** Cell-relative. The ground contact on a figure, the centre on a flat marker. */
  readonly anchor: { readonly x: number; readonly y: number };
  /** A repeatable tile rather than a one-shot image. */
  readonly tiles: 'horizontal' | 'both' | null;
  /** Where a horizontal stroke's centreline sits, cell-relative. */
  readonly centerlineY: number | null;
  readonly role: string | null;
  readonly state: string | null;
  readonly value: number | null;
}

export interface Atlas {
  /** The `<Name>` both files share. */
  readonly name: string;
  readonly sheetField: string;
  readonly cellWidth: number;
  readonly cellHeight: number;
  /** Generated by `Art/tools/make_placeholders.py`, not supplied art. */
  readonly placeholder: boolean;
  readonly notes: string | null;
  readonly sprites: readonly AtlasSprite[];
}

export class ArtError extends Error {
  override readonly name = 'ArtError';
}

export function parseAtlas(name: string, json: unknown): Atlas {
  const where = `${name}_atlas.json`;
  const root = record(json, where);
  const sprites = array(root['sprites'], `${where}: sprites`).map((entry, index) =>
    parseSprite(entry, `${where}: sprites[${index}]`),
  );
  if (sprites.length === 0) throw new ArtError(`${where}: has no sprites`);
  const ids = new Set<string>();
  for (const sprite of sprites) {
    if (ids.has(sprite.id)) throw new ArtError(`${where}: sprite id ${sprite.id} appears twice`);
    ids.add(sprite.id);
  }
  return {
    name,
    sheetField: string(root['sheet'], `${where}: sheet`),
    cellWidth: positive(root['cell_width'], `${where}: cell_width`),
    cellHeight: positive(root['cell_height'], `${where}: cell_height`),
    placeholder: root['placeholder'] === true,
    notes: typeof root['notes'] === 'string' ? root['notes'] : null,
    sprites,
  };
}

export function spriteIndex(atlas: Atlas, id: string): number {
  const index = atlas.sprites.findIndex((sprite) => sprite.id === id);
  if (index < 0) throw new ArtError(`${atlas.name}_atlas.json has no sprite ${id}`);
  return index;
}

/** The furthest right and down any sprite reaches, which the sheet must cover. */
export function atlasExtent(atlas: Atlas): { readonly width: number; readonly height: number } {
  let width = 0;
  let height = 0;
  for (const sprite of atlas.sprites) {
    width = Math.max(width, sprite.x + sprite.width);
    height = Math.max(height, sprite.y + sprite.height);
  }
  return { width, height };
}

function parseSprite(json: unknown, where: string): AtlasSprite {
  const entry = record(json, where);
  const anchor = record(entry['anchor'], `${where}: anchor`);
  const tiles = entry['tiles'];
  if (tiles !== undefined && tiles !== 'horizontal' && tiles !== 'both') {
    throw new ArtError(`${where}: tiles must be "horizontal" or "both"`);
  }
  return {
    id: string(entry['id'], `${where}: id`),
    x: nonNegative(entry['x'], `${where}: x`),
    y: nonNegative(entry['y'], `${where}: y`),
    width: positive(entry['width'], `${where}: width`),
    height: positive(entry['height'], `${where}: height`),
    anchor: { x: finite(anchor['x'], `${where}: anchor.x`), y: finite(anchor['y'], `${where}: anchor.y`) },
    tiles: tiles ?? null,
    centerlineY: entry['centerline_y'] === undefined ? null : finite(entry['centerline_y'], `${where}: centerline_y`),
    role: typeof entry['role'] === 'string' ? entry['role'] : null,
    state: typeof entry['state'] === 'string' ? entry['state'] : null,
    value: typeof entry['value'] === 'number' ? entry['value'] : null,
  };
}

// --- small readers, shared with manifest.ts ----------------------------------

export function record(value: unknown, where: string): Readonly<Record<string, unknown>> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new ArtError(`${where}: expected an object`);
  }
  return value as Record<string, unknown>;
}

export function array(value: unknown, where: string): readonly unknown[] {
  if (!Array.isArray(value)) throw new ArtError(`${where}: expected a list`);
  return value;
}

export function string(value: unknown, where: string): string {
  if (typeof value !== 'string' || value.length === 0) throw new ArtError(`${where}: expected a name`);
  return value;
}

export function finite(value: unknown, where: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) throw new ArtError(`${where}: expected a number`);
  return value;
}

export function positive(value: unknown, where: string): number {
  const number = finite(value, where);
  if (number <= 0) throw new ArtError(`${where}: must be above 0`);
  return number;
}

export function nonNegative(value: unknown, where: string): number {
  const number = finite(value, where);
  if (number < 0) throw new ArtError(`${where}: must not be negative`);
  return number;
}
